spring:
  jpa:
    hibernate.ddl-auto: update
    show-sql: false
    database-platform: org.hibernate.dialect.MySQL5Dialect
---
spring:
  profiles: production
  datasource:
      url: jdbc:mysql://fe-vi.com:3306/fadong?useUnicode=true&connectionCollation=utf8_general_ci&characterSetResults=utf8&characterEncoding=utf8
      username: root
      password: dandi1147
      driver-class-name: com.mysql.jdbc.Driver


