spring:
  jpa:
    hibernate.ddl-auto: update
    show-sql: false
    database-platform: org.hibernate.dialect.MySQL5Dialect
---
spring:
  profiles: local
  datasource:
    url: jdbc:mysql://localhost:3306/fadong?useUnicode=true&connectionCollation=utf8_general_ci&characterSetResults=utf8&characterEncoding=utf8
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver
FACEBOOK_APP_ID: 514013175372206
FACEBOOK_APP_SECRET: 40138e1e285c6ca347281fdf10e037ec
FACEBOOK_REDIRECT_URI: http://local.fe-vi.com:8080/token/login/callback
FACEBOOK_SCOPE: user_videos
---
spring:
  profiles: production
  datasource:
      url: jdbc:mysql://fe-vi.com:3306/fadong?useUnicode=true&connectionCollation=utf8_general_ci&characterSetResults=utf8&characterEncoding=utf8
      username: root
      password: dandi1147
      driver-class-name: com.mysql.jdbc.Driver
FACEBOOK_APP_ID: 664982483560405
FACEBOOK_APP_SECRET: b43ece70da3850e7751c2da470d3785d
FACEBOOK_REDIRECT_URI: http://fe-vi.com/token/login/callback
FACEBOOK_SCOPE: user_videos
---
spring:
  profiles: cafe24
  datasource:
      url: jdbc:mysql://localhost/munsangdong?useUnicode=true&connectionCollation=utf8_general_ci&characterSetResults=utf8&characterEncoding=utf8&?autoReconnect=true
      username: munsangdong
      password: 'e6/Uafq7AoEoJQ'
      driver-class-name: com.mysql.jdbc.Driver
      test-on-borrow: true
      validation-query: SELECT 1
FACEBOOK_APP_ID: 403677719733998
FACEBOOK_APP_SECRET: 4f29e57db1d00a28a324eab47ab31e8a
FACEBOOK_REDIRECT_URI: http://munsangdong.cafe24.com/token/login/callback
FACEBOOK_SCOPE: user_videos
---
spring:
  profiles: cafe24local
  datasource:
      url: jdbc:mysql://munsangdong.cafe24.com/munsangdong?useUnicode=true&connectionCollation=utf8_general_ci&characterSetResults=utf8&characterEncoding=utf8
      username: munsangdong
      password: 'e6/Uafq7AoEoJQ'
      driver-class-name: com.mysql.jdbc.Driver
FACEBOOK_APP_ID: 403677719733998
FACEBOOK_APP_SECRET: 4f29e57db1d00a28a324eab47ab31e8a
FACEBOOK_REDIRECT_URI: http://munsangdong.cafe24.com/token/login/callback
FACEBOOK_SCOPE: user_videos

